### ISSUE TITLE
wrong answer太简单了吧，能否增加一些提示

### ISSUE THREAD

**Issue by kworldljd** [ultmaster/eoj3#29]
做了各题目，不论是test1还是test4失败都提示wrong answer，完全无从下手。能否增加部分提示。input。。。expect output。

**Comment by ultmaster** [comment]
这个功能有。。。

**Comment by kworldljd** [comment]
> 这个功能有。。。

在哪里呀。没找到，请明示。另外有没有使用指南这样的东东，新手有点蒙呀，谢谢。

**Comment by kworldljd** [comment]
另外那个qq群申请加入“用户交流群：691713742。（入群问题提示：EOJ 全称，注意大小写）”，输入EOJ，提示密码不对:(.

**Comment by ultmaster** [comment]
如果没找到说明这道题的管理员不让你看数据。（这个是可以设置的）
EOJ 全称不是 EOJ。
使用指南没有的。见 README。

**Comment by kworldljd** [comment]
通过点#的链接，里面的测试报告有测试用例。我将测试用例拿到本机执行，调整程序后本机执行ok，重新提交时，还是不通过，显示的执行结果与本机的不一致。（期望值8，本机执行8，测试机上是6，还是原来的，防止手误，我将提交的代码拷下来，在本机执行，也是ok的），是不是有缓存呀？

**Comment by kworldljd** [comment]
提交 #1540962
